/**
 * Writes README.md. The whole profile is one centred paragraph of images:
 * inline images with no whitespace between them sit edge to edge, and a
 * <br> starts the next row, so the sliced boards reassemble exactly.
 *
 * Each tile is a <picture>: at 1280px and up GitHub's README column fits
 * the 744px board, so it gets the cell with the circuit; below that it gets
 * the bare card, which wraps cleanly on a phone.
 *
 * The <img> fallbacks carry a width but no height: GitHub caps images at
 * max-width: 100% without height: auto, so a fixed height would squash any
 * image a phone shrinks.
 */
import { BOARD_W, type Board } from './boards';
import { HERO_W } from './hero';
import type { TileSize } from './render';
import { tileFile } from './render';
import { site } from './data';

const WIDE = '(min-width: 1280px)';
const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function tile(id: string, alt: string, href: string | undefined, size: TileSize): string {
    const src = (variant: 'wire' | 'card', theme: 'dark' | 'light') => `./assets/tiles/${tileFile(id, variant, theme)}`;
    const picture =
        `<picture>` +
        `<source media="${WIDE} and (prefers-color-scheme: dark)" srcset="${src('wire', 'dark')}" width="${size.wire.width}" height="${size.wire.height}" />` +
        `<source media="${WIDE} and (prefers-color-scheme: light)" srcset="${src('wire', 'light')}" width="${size.wire.width}" height="${size.wire.height}" />` +
        `<source media="(prefers-color-scheme: dark)" srcset="${src('card', 'dark')}" />` +
        `<img src="${src('card', 'light')}" alt="${esc(alt)}" width="${size.card.width}" align="top" />` +
        `</picture>`;
    return href ? `<a href="${esc(href)}">${picture}</a>` : picture;
}

export function readme(boards: Board[], sizes: Record<string, TileSize>): string {
    for (const board of boards)
        for (const row of board.rows) {
            const width = row.tiles.reduce((sum, t) => sum + t.width, 0);
            if (width !== BOARD_W) throw new Error(`${board.id}: a row is ${width}px wide, not ${BOARD_W}px`);
        }

    const hero =
        `<picture>` +
        `<source media="(prefers-color-scheme: dark)" srcset="./assets/hero-dark.svg" />` +
        `<img src="./assets/hero-light.svg" alt="${esc(`${site.name} — ${site.role}`)}" width="${HERO_W}" />` +
        `</picture>`;

    const rows = boards.flatMap((board) =>
        board.rows.map((row) => row.tiles.map((t) => tile(t.id, t.alt, t.href, sizes[t.id]!)).join('')),
    );

    return `<!-- Generated by \`bun run index.ts\` from src/ — edit there, not here. -->

<p align="center">${[hero, ...rows].join('<br />')}</p>

<p align="center"><sub>re-rendered every 12 hours by github actions · bun + puppeteer · design tokens from <a href="${site.url}">${site.url.replace('https://', '')}</a></sub></p>
`;
}
